[workspace]
members = [
    "crates/topos-cli",
    "crates/topos-lib",
    # "crates/topos-ts",
    "crates/topos-py",
]
resolver = "3"

[workspace.dependencies]
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
regex = "1.11.1"
